image: eclipse-temurin:21-jdk-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  SPRING_PROFILES_ACTIVE: test

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/
    - HandyHive-Backend/.gradle/

stages:
  - test

backend-test:
  stage: test
  script:
    - echo "🚀 Starting Pipeline..."
    - cd HandyHive-Backend
    - chmod +x gradlew
    - ./gradlew clean test
  artifacts:
    when: always
    reports:
      junit: HandyHive-Backend/build/test-results/test/**/TEST-*.xml
